[ignore]
extensions="gv~"

[latex]
extensions="tex"
command="latexmk -pdf {name.ext}"

[graphviz]
extensions="gv"
command="dot -Tpdf {rpath} > {rname}.pdf"

[gnuplot]
extensions="gp gnuplot"
command="gnuplot {rpath}"


[pdf]
extensions="pdf"
extra_variables="pdfinfo {rpath}"
command="echo {Title}"

